laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', function () {
        if (auth('cadastros')->check()) {
            return redirect()->route('sumario');
        } else {
            return redirect()->route('cadastros.login');
        }
    });
    Route::get('cadastros/login', 'Cadastros\Auth\AuthController@showLoginForm')->name('cadastros.login');
    Route::get('cadastros/esqueci-minha-senha', 'Cadastros\Auth\PasswordController@showResetRequestForm')->name('cadastros.reset-request');
    Route::get('cadastros/redefinir-senha/{token}', 'Cadastros\Auth\PasswordController@showResetForm')->name('cadastros.reset');
    Route::get('cadastros/novo-cadastro', 'Cadastros\Auth\AuthController@showCreateForm')->name('cadastros.create');
    Route::get('cadastros/alterar-cadastro/{user}', 'Cadastros\Auth\AuthController@showUpdateForm')->name('cadastros.update');
    Route::get('conteudo-restrito', function () {
        return view('frontend.conteudo-restrito');
    })->name('conteudo-restrito');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'CookiesController@postCookies')->name('aceite-de-cookies.post');

    // Cadastros LOGADOS
    Route::group(['middleware' => 'cadastros.auth'], function () {
        Route::get('sumario', 'SumarioController@index')->name('sumario');
        Route::get('capitulo/{capitulo}/{post}/{proximo?}', 'SumarioController@showPost')->name('post');
        Route::get('{cadastro}/{post}/concluido', 'SumarioController@postConcluido')->name('post.concluido');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('usuarios', 'UsuariosController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('contatos', 'ContatosController');
        Route::resource('capitulos', 'CapitulosController');
        Route::resource('capitulos.posts', 'CapitulosPostsController');
        Route::resource('emails', 'EmailsController');
        Route::get('cadastros', 'CadastrosController@index')->name('painel.cadastros.index');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth PAINEL
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });

    // Auth CADASTROS
    Route::group([
        'prefix' => 'cadastros',
        'namespace' => 'Cadastros',
    ], function () {
        Route::post('login', 'Auth\AuthController@login')->name('cadastros.login');
        Route::post('cadastro', 'Auth\AuthController@create')->name('register.post');
        Route::post('cadastro/{user}', 'Auth\AuthController@update')->name('update.post');
        Route::post('esqueci-minha-senha', 'Auth\PasswordController@sendResetLinkEmail')->name('reset-request.post');
        Route::post('redefinicao-de-senha', 'Auth\PasswordController@reset')->name('reset.post');
        Route::get('logout', 'Auth\AuthController@logout')->name('cadastros.logout');
    });
});

laravel/app/Models/Capitulo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Capitulo extends Model
{
    protected $table = 'capitulos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }
}

laravel/app/Http/Controllers/Painel/CapitulosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CapitulosRequest;
use App\Models\Capitulo;

class CapitulosController extends Controller
{
    public function index()
    {
        $capitulos = Capitulo::ordenados()->get();

        return view('painel.capitulos.index', compact('capitulos'));
    }

    public function create()
    {
        return view('painel.capitulos.create');
    }

    public function store(CapitulosRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            Capitulo::create($input);

            return redirect()->route('painel.capitulos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Capitulo $capitulo)
    {
        return view('painel.capitulos.edit', compact('capitulo'));
    }

    public function update(CapitulosRequest $request, Capitulo $capitulo)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $capitulo->update($input);

            return redirect()->route('painel.capitulos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Capitulo $capitulo)
    {
        try {
            $capitulo->delete();

            return redirect()->route('painel.capitulos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/capitulos/posts/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Capítulo: {{ $capitulo->titulo }} |</small> Adicionar Post</h2>
</legend>

{!! Form::model($capitulo, [
'route' => ['painel.capitulos.posts.store', $capitulo->id],
'method' => 'post',
'files' => true])
!!}

@include('painel.capitulos.posts.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/capitulos/posts/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Capítulo: {{ $capitulo->titulo }} |</small> Editar Post</h2>
</legend>

{!! Form::model($posts, [
'route' => ['painel.capitulos.posts.update', $capitulo->id, $posts->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.capitulos.posts.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/capitulos/posts/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo_post', 'Título') !!}
    {!! Form::text('titulo_post', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::textarea('texto', null, ['class' => 'form-control ckeditor', 'data-editor' => 'textBlog']) !!}

    <p class="obs" style="color:red;margin:10px 0; font-style:italic;">Usar <strong>Título 2</strong> para subtítulos</p>
    <p class="obs" style="color:red;margin:0 0; font-style:italic;">Usar <strong>Título 3</strong> para pontos-chave</p>
    <p class="obs" style="color:red;margin:10px 0; font-style:italic;">Usar <strong>Título 6</strong> para legendas</p>
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.capitulos.posts.index', $capitulo->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/capitulos/posts/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        <small>Capítulo: {{ $capitulo->titulo }} |</small> Posts
        <a href="{{ route('painel.capitulos.posts.create', $capitulo->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Post</a>
    </h2>
</legend>


@if(!count($posts))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="capitulos_posts">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Título</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($posts as $post)
        <tr class="tr-row" id="{{ $post->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td>{{ $post->titulo_post }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.capitulos.posts.destroy', $capitulo->id, $post->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.capitulos.posts.edit', [$capitulo->id, $post->id]) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection