laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', function () {
        if (auth('cadastros')->check()) {
            return redirect()->route('sumario');
        } else {
            return redirect()->route('cadastros.login');
        }
    });
    Route::get('cadastros/login', 'Cadastros\Auth\AuthController@showLoginForm')->name('cadastros.login');
    Route::get('cadastros/esqueci-minha-senha', 'Cadastros\Auth\PasswordController@showResetRequestForm')->name('cadastros.reset-request');
    Route::get('cadastros/redefinir-senha/{token}', 'Cadastros\Auth\PasswordController@showResetForm')->name('cadastros.reset');
    Route::get('cadastros/novo-cadastro', 'Cadastros\Auth\AuthController@showCreateForm')->name('cadastros.create');
    Route::get('cadastros/alterar-cadastro/{user}', 'Cadastros\Auth\AuthController@showUpdateForm')->name('cadastros.update');
    Route::get('conteudo-restrito', function () {
        return view('frontend.conteudo-restrito');
    })->name('conteudo-restrito');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'CookiesController@postCookies')->name('aceite-de-cookies.post');

    // Cadastros LOGADOS
    Route::group(['middleware' => 'cadastros.auth'], function () {
        Route::get('sumario', 'SumarioController@index')->name('sumario');
        Route::get('capitulo/{capitulo}/{post}/{proximo?}', 'SumarioController@showPost')->name('post');
        Route::get('{cadastro}/{post}/concluido', 'SumarioController@postConcluido')->name('post.concluido');
    });

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::resource('usuarios', 'UsuariosController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('contatos', 'ContatosController');
        Route::resource('capitulos', 'CapitulosController');
        Route::resource('capitulos.posts', 'CapitulosPostsController');
        Route::resource('emails', 'EmailsController');
        Route::get('cadastros', 'CadastrosController@index')->name('painel.cadastros.index');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth PAINEL
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });

    // Auth CADASTROS
    Route::group([
        'prefix' => 'cadastros',
        'namespace' => 'Cadastros',
    ], function () {
        Route::post('login', 'Auth\AuthController@login')->name('cadastros.login');
        Route::post('cadastro', 'Auth\AuthController@create')->name('register.post');
        Route::post('cadastro/{user}', 'Auth\AuthController@update')->name('update.post');
        Route::post('esqueci-minha-senha', 'Auth\PasswordController@sendResetLinkEmail')->name('reset-request.post');
        Route::post('redefinicao-de-senha', 'Auth\PasswordController@reset')->name('reset.post');
        Route::get('logout', 'Auth\AuthController@logout')->name('cadastros.logout');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $cookies = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('cookies'));
    }
}

laravel/app/Http/Controllers/Painel/CadastrosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Cadastro;

class CadastrosController extends Controller
{
    public function index()
    {
        $cadastros = Cadastro::liberado()->orderBy('nome', 'asc')->get();

        return view('painel.cadastros.index', compact('cadastros'));
    }
}

laravel/app/Http/Controllers/Painel/CapitulosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CapitulosRequest;
use App\Models\Capitulo;

class CapitulosController extends Controller
{
    public function index()
    {
        $capitulos = Capitulo::ordenados()->get();

        return view('painel.capitulos.index', compact('capitulos'));
    }

    public function create()
    {
        return view('painel.capitulos.create');
    }

    public function store(CapitulosRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            Capitulo::create($input);

            return redirect()->route('painel.capitulos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Capitulo $capitulo)
    {
        return view('painel.capitulos.edit', compact('capitulo'));
    }

    public function update(CapitulosRequest $request, Capitulo $capitulo)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            $capitulo->update($input);

            return redirect()->route('painel.capitulos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Capitulo $capitulo)
    {
        try {
            $capitulo->delete();

            return redirect()->route('painel.capitulos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CapitulosPostsController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CapitulosPostsRequest;
use App\Models\Capitulo;
use App\Models\CapituloPosts;

class CapitulosPostsController extends Controller
{
    public function index(Capitulo $capitulo)
    {
        $posts = CapituloPosts::capitulo($capitulo->id)->ordenados()->get();

        return view('painel.capitulos.posts.index', compact('capitulo', 'posts'));
    }

    public function create(Capitulo $capitulo)
    {
        return view('painel.capitulos.posts.create', compact('capitulo'));
    }

    public function store(CapitulosPostsRequest $request, Capitulo $capitulo)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo_post, "-");
            $input['capitulo_id'] = $capitulo->id;

            CapituloPosts::create($input);

            return redirect()->route('painel.capitulos.posts.index', $capitulo->id)->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Capitulo $capitulo, CapituloPosts $posts)
    {
        return view('painel.capitulos.posts.edit', compact('capitulo', 'posts'));
    }

    public function update(CapitulosPostsRequest $request, Capitulo $capitulo, CapituloPosts $posts)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo_post, "-");
            $input['capitulo_id'] = $capitulo->id;

            $posts->update($input);

            return redirect()->route('painel.capitulos.posts.index', $capitulo->id)->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Capitulo $capitulo, CapituloPosts $posts)
    {
        try {
            $posts->delete();

            return redirect()->route('painel.capitulos.posts.index', $capitulo->id)->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracao;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracao::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracao $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracao::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatosRequest;
use App\Models\Contato;

class ContatosController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contatos.edit', compact('contato'));
    }

    public function update(ContatosRequest $request, Contato $contato)
    {
        try {
            $input = $request->all();

            $contato->update($input);

            return redirect()->route('painel.contatos.index')->with('success', 'Informações alteradas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/EmailsController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\EmailsRequest;
use App\Models\Email;

class EmailsController extends Controller
{
    public function index()
    {
        $emails = Email::orderBy('email', 'asc')->get();

        return view('painel.emails.index', compact('emails'));
    }

    public function create()
    {
        return view('painel.emails.create');
    }

    public function store(EmailsRequest $request)
    {
        try {
            $input = $request->all();

            Email::create($input);

            return redirect()->route('painel.emails.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Email $email)
    {
        return view('painel.emails.edit', compact('email'));
    }

    public function update(EmailsRequest $request, Email $email)
    {
        try {
            $input = $request->all();

            $email->update($input);

            return redirect()->route('painel.emails.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Email $email)
    {
        try {
            $email->delete();

            return redirect()->route('painel.emails.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Helpers\CropImage;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class PainelController extends Controller
{
    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

    private $image_config = [
        'width'  => 980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/editor/'
    ];

    public function imageUpload(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/Painel/PoliticaDePrivacidadeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\PoliticaDePrivacidadeRequest;
use App\Models\PoliticaDePrivacidade;

class PoliticaDePrivacidadeController extends Controller
{
    public function index()
    {
        $registro = PoliticaDePrivacidade::first();

        return view('painel.politica-de-privacidade.edit', compact('registro'));
    }

    public function update(PoliticaDePrivacidadeRequest $request, PoliticaDePrivacidade $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.politica-de-privacidade.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
<div class="alert alert-block alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {!! session('success') !!}
</div>
@endif

@if($errors->any())
<div class="alert alert-block alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    @foreach($errors->all() as $error)
    {!! $error !!}<br>
    @endforeach
</div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.politica-de-privacidade*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}" class="link-nav-painel">Política de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}" class="link-nav-painel">Relatório de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

    <li class="dropdown @if(Tools::routeIs(['painel.emails*', 'painel.cadastros*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.emails*')) class="active" @endif>
                <a href="{{ route('painel.emails.index') }}">E-mails Liberados</a>
            </li>
            <li @if(Tools::routeIs('painel.cadastros*')) class="active" @endif>
                <a href="{{ route('painel.cadastros.index') }}">Cadastros Ativos</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.capitulos*')) class="active" @endif>
        <a href="{{ route('painel.capitulos.index') }}">Capítulos</a>
    </li>

    <li @if(Tools::routeIs('painel.contatos.index')) class="active" @endif>
        <a href="{{ route('painel.contatos.index') }}">Informações de Contato</a>
    </li>

</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>

<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>

</body>

</html>